// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqJekN4QYWe51L2Czpc9nvCkpLb6lzUYg',
    appId: '1:241973761970:web:48b97a5565993a939676ab',
    messagingSenderId: '241973761970',
    projectId: 'happyfinance-9885f',
    authDomain: 'happyfinance-9885f.firebaseapp.com',
    storageBucket: 'happyfinance-9885f.firebasestorage.app',
    measurementId: 'G-GNLLFE48XS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlOYUBvTo44MITfrO0oAlbuqWbMrH2pEM',
    appId: '1:241973761970:android:d3ec0c3045f0b65e9676ab',
    messagingSenderId: '241973761970',
    projectId: 'happyfinance-9885f',
    storageBucket: 'happyfinance-9885f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7fbmrYWLRuhm4M-8svwEn7GbJmiE5JB4',
    appId: '1:241973761970:ios:53c86b73fb74a6dd9676ab',
    messagingSenderId: '241973761970',
    projectId: 'happyfinance-9885f',
    storageBucket: 'happyfinance-9885f.firebasestorage.app',
    iosBundleId: 'com.localtechindonesia.happyfinance-mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7fbmrYWLRuhm4M-8svwEn7GbJmiE5JB4',
    appId: '1:241973761970:ios:c3ebe50002d379089676ab',
    messagingSenderId: '241973761970',
    projectId: 'happyfinance-9885f',
    storageBucket: 'happyfinance-9885f.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqJekN4QYWe51L2Czpc9nvCkpLb6lzUYg',
    appId: '1:241973761970:web:5599a3f132d5fb939676ab',
    messagingSenderId: '241973761970',
    projectId: 'happyfinance-9885f',
    authDomain: 'happyfinance-9885f.firebaseapp.com',
    storageBucket: 'happyfinance-9885f.firebasestorage.app',
    measurementId: 'G-RSY0RYFWKP',
  );
}
