// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:happyfinance_mobile/domains/auth/hive/auth_data_hive.dart';
import 'package:hive_ce/hive_ce.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AuthDataHiveAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AuthDataHiveAdapter());
  }
}
